CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(250) NOT NULL,
    password   VARCHAR(250) NOT NULL,
    email      VARCHAR(250) NOT NULL UNIQUE,
    created_on TIMESTAMP    NOT NULL
);

CREATE TABLE quotes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_id BIGINT        NOT NULL DEFAULT -1 REFERENCES users (id) ON DELETE SET DEFAULT,
    content    VARCHAR(1000) NOT NULL,
    updated_on TIMESTAMP     NOT NULL
);

CREATE TABLE quote_vote
(
    quote_id    BIGINT    NOT NULL REFERENCES quotes (id) ON DELETE CASCADE,
    voter_id    BIGINT    NOT NULL DEFAULT -1 REFERENCES users (id) ON DELETE SET DEFAULT,
    is_positive BOOLEAN   NOT NULL,
    updated_on  TIMESTAMP NOT NULL,
    total_score INTEGER   NOT NULL,
    CONSTRAINT pk_quote_vote_quote_id_voter_id PRIMARY KEY (quote_id, voter_id)
);