DROP TABLE quote_vote;
DROP TABLE quotes;
DROP TABLE users;

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(250) NOT NULL,
    password   VARCHAR(250) NOT NULL,
    email      VARCHAR(250) NOT NULL UNIQUE,
    created_on TIMESTAMP    NOT NULL
);

CREATE TABLE quotes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_id BIGINT        NOT NULL REFERENCES users (id) ON DELETE NO ACTION,
    content    VARCHAR(1000) NOT NULL,
    updated_on TIMESTAMP     NOT NULL
);

CREATE TABLE quote_vote
(
    quote_id    BIGINT    NOT NULL REFERENCES quotes (id) ON DELETE CASCADE,
    voter_id    BIGINT    NOT NULL REFERENCES users (id) ON DELETE NO ACTION,
    is_positive BOOLEAN   NOT NULL,
    updated_on  TIMESTAMP NOT NULL,
    total_score INTEGER   NOT NULL,
    CONSTRAINT pk_quote_vote_quote_id_voter_id PRIMARY KEY (quote_id, voter_id)
);

INSERT INTO users(name, password, email, created_on)
VALUES ('TestName_1', 'TestPassword_1', 'Test_1@email.ru', '2021-01-01T10:10:10'),
       ('TestName_2', 'TestPassword_2', 'Test_2@email.ru', '2022-02-02T10:10:10');

INSERT INTO quotes (creator_id, content, updated_on)
VALUES (1, 'TestContent_1', '2021-01-01T10:10:10'),
       (2, 'TestContent_2', '2022-02-02T10:10:10'),
       (2, 'TestContent_3', '2022-03-03T10:10:10');

INSERT INTO quote_vote (quote_id, voter_id, is_positive, updated_on, total_score)
VALUES (2, 1, true, '2021-01-01T10:10:10', ),
       (3, 1, false, '2021-01-01T10:10:10', );